version: '3.0'
services:
  mysql:
    image: "mysql"
    restart: "always"
    command: "--default-authentication-plugin=mysql_native_password"
    environment:
      MYSQL_ROOT_PASSWORD: "root"
    volumes:
      - "./script/:/docker-entrypoint-initdb.d/"
    ports:
      - "3306:3306"
  redis:
    image: "redis"
    environment:
      - "ALLOW_EMPTY_PASSWORD=yes"
    ports:
      - "6379:6379"
  etcd:
    image: "bitnami/etcd:latest"
    environment:
      - "ALLOW_NONE_AUTHENTICATION=yes"
    ports:
      - "2379:2379"